"""added virusscanresult table

Revision ID: 9c0413cd7f69
Revises: de915b439eab
Create Date: 2025-12-05 16:04:03.855021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c0413cd7f69'
down_revision: Union[str, Sequence[str], None] = 'de915b439eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf', sa.Column('scan_results_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'pdf', 'virusscanresult', ['scan_results_id'], ['id'])
    op.drop_column('pdf', 'virustotal_scan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf', sa.Column('virustotal_scan', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pdf', type_='foreignkey')
    op.drop_column('pdf', 'scan_results_id')
    # ### end Alembic commands ###
