@startuml Database Schema
'skinparam linetype ortho

entity Publication{
    *id: uuid4 <<generated>>
    *analyse_refs: boolean = True
    name: varchar(n)
    'university
    'faculty
    'programme
    year: int
    class: enum
    raw_text: text
    --
    filename: pdf_id <<FK>>
}

entity Pdf {
    *id: uuid4 <<generated>>
    parsed: boolean = False
}

entity PublicationAuthorLinktable{
    *id: uuid4 <<generated>>
    --
    *publication_id: publication_id <<FK>>
    *author_id: author_id <<FK>>
}

entity Author{
    *id: uuid4 <<generated>>
    ORCID: ?
    name: varchar(n)
}

entity Citation{
    *id: uuid4 <<generated>>
    raw_text: text
    --
    *in_publication: publication_id <<FK>>
    *reference: publication_id <<FK>>
}

Publication ||--|| Pdf: pdf_id
Publication }|-- PublicationAuthorLinktable: publication_id
Author }|-- PublicationAuthorLinktable: author_id

Publication ||--|{ FetchResult
FetchResult }|--|| FetchMethod

Publication ||--|{ Citation: in_publication
Publication ||--|{ Citation: reference

Citation ||--|{ CitationClass
CitationClass }|--|| CitationClassifier
Citation ||--|{ CitationEvaluation
CitationEvaluation }|--|| CitationEvaluator

@enduml